matches:

  # ==============================================================================
  # MySQL Commands
  # ==============================================================================
  # User Control
  - trigger: ':mysql add user'
    replace: "CREATE USER 'ttndev'@'%' IDENTIFIED BY 'ttndev'; GRANT ALL PRIVILEGES ON *.* TO 'ttndev'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

  # Import
  - trigger: ':mysql import'
    replace: 'sudo mysql -u ttndev -p nail_dev < /mnt/c/Users/ttnde/Downloads/Telegram\ Desktop/top1.sql'

  # Backup  
  - trigger: ':mysql backup tb struct'
    replace: 'mysqldump -u root -p -d [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_struct_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql backup tb data'
    replace: 'mysqldump -u root -p -t [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_data_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql backup tb all'
    replace: 'mysqldump -u root -p -t [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'
          
  - trigger: ':mysql backup db one'
    replace: 'mysqldump -u root -p [db] > /home/ttndev/backups/mysql/archive/db_[db]_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ":mysql backup db all"
    replace: "mysqldump -u root -p --all-databases > /home/ttndev/backups/mysql/archive/db_all_{{timestamp}}.sql"
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ":mysql show users"
    replace: "SELECT user, host FROM mysql.user;"
  
  - trigger: ":mysql show users"
    replace: "SELECT user, host FROM mysql.user;"
  
  - trigger: ":mysql show grants"
    replace: "SHOW GRANTS FOR 'ttndev'@'%';"
  
  - trigger: ":mysql grant all"
    replace: "GRANT ALL PRIVILEGES ON `docker-setup`.* TO `ttndev`@`%`;"
