matches:
  # ==============================================================================
  # MySQL Commands
  # ==============================================================================
  - trigger: ':mysql list'
    replace: |
      mysql add ser
      mysql im
      mysql bk tb struct
      mysql bk tb data
      mysql bk tb all
      mysql bk db one
      mysql bk db all
      mysql sh users
      mysql sh grant
      mysql grant all

  # User Control
  - trigger: ':mysql add user'
    replace: "CREATE USER 'ttndev'@'%' IDENTIFIED BY 'ttndev'; GRANT ALL PRIVILEGES ON *.* TO 'ttndev'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

  # Import
  - trigger: ':mysql import'
    replace: 'sudo mysql -u ttndev -p nail_dev < /mnt/c/Users/ttnde/Downloads/Telegram\ Desktop/top1.sql'

  # Backup
  - trigger: ':mysql bk tb struct'
    replace: 'mysqldump -u root -p<pass> -d [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_struct_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql bk tb data'
    replace: 'mysqldump -u root -p<pass> -t [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_data_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql bk tb all'
    replace: 'mysqldump -uroot -p<pass> -t [db] [tb] > /home/ttndev/backups/mysql/archive/db_[db]_tb_[tb]_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql bk db one'
    replace: 'mysqldump -u root -p<pass> [db] > /home/ttndev/backups/mysql/archive/db_[db]_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql bk db all'
    replace: 'mysqldump -u root -p<pass> --all-databases > /home/ttndev/backups/mysql/archive/db_all_{{timestamp}}.sql'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%m_%d_%Y_%H_%M_%S'

  - trigger: ':mysql sh users'
    replace: 'SELECT user, host FROM mysql.user;'

  - trigger: ':mysql sh grants'
    replace: "SHOW GRANTS FOR 'ttndev'@'%';"

  - trigger: ':mysql grant all'
    replace: 'GRANT ALL PRIVILEGES ON `docker-setup`.* TO `ttndev`@`%`;'
